# Generated by Django 5.2.5 on 2025-09-10 15:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('question_count', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('question_count', models.IntegerField(default=0)),
                ('asked_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_word', models.CharField(max_length=100)),
                ('target_word', models.CharField(max_length=100)),
                ('source_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_list', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='vocab.quizlist')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(max_length=100)),
                ('answer_time', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='vocabulary_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='vocab.vocabularylist'),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('goal_type', models.CharField(choices=[('minutes_per_day', 'Minutes per day'), ('reviews_per_day', 'Reviews per day'), ('quiz', 'Quiz')], max_length=20)),
                ('goal_value', models.PositiveIntegerField(default=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='vocab.quizlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='vocab.vocabularylist')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReviewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_review_counters', to=settings.AUTH_USER_MODEL)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_review_counters', to='vocab.studysession')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='vocab_daily_user_id_86880c_idx'), models.Index(fields=['study_session', 'date'], name='vocab_daily_study_s_fdf6c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'study_session'), name='uniq_user_date_session_reviews')],
            },
        ),
        migrations.CreateModel(
            name='DailyMinuteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_minute_counters', to=settings.AUTH_USER_MODEL)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_minute_counters', to='vocab.studysession')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='vocab_daily_user_id_42034c_idx'), models.Index(fields=['study_session', 'date'], name='vocab_daily_study_s_10c27f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'study_session'), name='uniq_user_date_session_minutes')],
            },
        ),
        migrations.CreateModel(
            name='ActiveStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='vocab.studysession')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'started_at'], name='vocab_activ_user_id_22e8c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_active_session_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_occurrences', models.IntegerField(default=0)),
                ('last_occurrence', models.IntegerField(default=0)),
                ('alpha', models.FloatField(default=0.1)),
                ('beta', models.FloatField(default=0.5)),
                ('is_asked_in_quiz', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_memories', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabulary')),
                ('vocabulary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memories', to='vocab.vocabularylist')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'vocabulary'], name='vocab_userm_user_id_9b9434_idx')],
                'unique_together': {('user', 'vocabulary', 'vocabulary_list')},
            },
        ),
    ]
