# Generated by Django 5.2.5 on 2025-09-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
